spring.application.name=ssr
spring.datasource.url=jdbc:mysql://localhost:3306/pruebas
spring.datasource.username=user
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
# Para mostrar los mensajes de error completos en la respuesta HTTP
# (eliminar estas líneas al poner la app en producción)
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
